image: python:3.6-alpine

stages:
  - test

test:
  stage: test
  script:
    - pip install pytest-cov msgpack-python
    - python setup.py develop
    - py.test --cov=src/ahocorapy/ tests/ahocorapy_test.py

