stages:
  - test

test-py36:
  image: python:3.6-alpine
  stage: test
  script:
    - pip install tox
    - tox -e py36

test-py35:
  image: python:3.5-alpine
  stage: test
  script:
    - pip install tox
    - tox -e py35

test-py34:
  image: python:3.4-alpine
  stage: test
  script:
    - pip install tox
    - tox -e py34

test-py33:
  image: python:3.3-alpine
  stage: test
  script:
    - pip install tox
    - tox -e py33

test-py27:
  image: python:2.7-alpine
  stage: test
  script:
    - pip install tox
    - tox -e py27

test-pypy:
  image: pypy:slim
  stage: test
  script:
    - pip install tox
    - tox -e pypy

test-jython:
  image: mcandre/docker-jython
  stage: test
  script:
    - jython -m ensurepip
    - pip install tox
    - tox -e jython
