language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"

install:
  - pip install pytest-cov msgpack-python python-coveralls
  - pip install -e .
  
script:
  - py.test --pep8 src/ahocorapy/ --cov src/ahocorapy/ --cov-report term-missing  tests/ahocorapy_test.py

after_success:
  - coveralls